# -*- coding: utf-8 -*-
"""work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XdBoqCT2rXruW5pXH4MjA63OZg43i7X

Import libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Example dataset"""

data = {
    "Product": ["A", "B", "C", "D", "E"],
    "Sales": [120, 340, 230, 150, 400]
}

df = pd.DataFrame(data)

"""Bar chart"""

plt.figure(figsize=(6,4))
sns.barplot(x="Product", y="Sales", data=df)
plt.title("Sales by Product")
plt.show()